#!/bin/bash
clear
mkdir -p /root/modem
wget https://github.com/Haris131/e3372/blob/main/balong-nvtool?raw=true -O /root/modem/balong-nvtool
wget https://raw.githubusercontent.com/Haris131/e3372/main/modem -O /root/modem/modem
chmod +x /root/modem/balong-nvtool
chmod +x /root/modem/modem
clear
echo -e "Buka /root/modem"
echo -e "Ketik ./modem"
echo -e "Selesai"
